// Code generated by goyacc qapi-schema.y. DO NOT EDIT.

//line qapi-schema.y:2
package main

import __yyfmt__ "fmt"

//line qapi-schema.y:2

// delete the fmt import if it interferes with the parsing process

//import "fmt"

const STR = 57346
const NUMBER = 57347
const SIZE = 57348
const BOOL = 57349
const NULL = 57350
const ANY = 57351
const QTYPE = 57352
const STRUCT = 57353
const INT = 57354
const INT8 = 57355
const INT32 = 57356
const INT64 = 57357
const UINT8 = 57358
const UINT16 = 57359
const UINT32 = 57360
const UINT64 = 57361
const INCLUDE = 57362
const PRAGMA = 57363
const ENUM = 57364
const UNION = 57365
const ALTERNATE = 57366
const COMMAND = 57367
const EVENT = 57368

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STR",
	"NUMBER",
	"SIZE",
	"BOOL",
	"NULL",
	"ANY",
	"QTYPE",
	"STRUCT",
	"INT",
	"INT8",
	"INT32",
	"INT64",
	"UINT8",
	"UINT16",
	"UINT32",
	"UINT64",
	"INCLUDE",
	"PRAGMA",
	"ENUM",
	"UNION",
	"ALTERNATE",
	"COMMAND",
	"EVENT",
	"';'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line qapi-schema.y:136
